# Generated by Django 2.0.7 on 2018-07-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180712_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagegallery',
            options={'verbose_name': 'Gallery image', 'verbose_name_plural': 'Gallery images'},
        ),
    ]
