# Generated by Django 2.0.7 on 2018-07-19 18:19

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepagecoverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecoverimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='home.HomePage'),
        ),
    ]
