# Generated by Django 2.0.7 on 2018-07-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('home', '0014_auto_20180719_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(null=True),
        ),
    ]
