# Generated by Django 2.0.7 on 2018-07-21 18:39

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180720_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=8)),
                ('country', django_countries.fields.CountryField(default='BE', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['city'],
            },
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Address')),
                ('name', models.CharField(max_length=64, verbose_name='location name')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['name'],
            },
            bases=('home.address', wagtail.search.index.Indexed),
        ),
    ]
