# Generated by Django 2.0.7 on 2018-08-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_aboutpage_aboutpagequestion_discoverypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='date',
        ),
    ]
