# Generated by Django 2.0.7 on 2018-08-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_homepage_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
