# Generated by Django 2.0.7 on 2018-08-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20180821_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Location')),
            ],
        ),
    ]
