# Generated by Django 2.0.7 on 2018-08-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0027_healthhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthHouseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Location')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Health House data',
            },
        ),
        migrations.AlterModelOptions(
            name='healthhouse',
            options={'verbose_name': 'Health House', 'verbose_name_plural': 'Health House'},
        ),
    ]
