# Generated by Django 2.0.7 on 2018-08-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20180821_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthhousesettings',
            name='tagline',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
