# Generated by Django 2.0.7 on 2018-08-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_healthhousesettings_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthHouseRelatedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('title', models.IntegerField(choices=[(1, 'Facebook'), (2, 'Twitter'), (3, 'LinkedIn'), (4, 'Youtube'), (5, 'Instagram')], verbose_name='Link naar')),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_links', to='home.HealthHouseSettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
