# Generated by Django 2.0.7 on 2018-08-21 10:32

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_healthhouserelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthhouserelatedlink',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_links', to='home.HealthHouseSettings'),
        ),
    ]
