# Generated by Django 2.0.7 on 2018-08-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20180821_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthhouse',
            name='location',
        ),
        migrations.AddField(
            model_name='healthhousesettings',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='healthhousesettings',
            name='phone_number',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.DeleteModel(
            name='HealthHouse',
        ),
    ]
