# Generated by Django 2.0.7 on 2018-08-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20180821_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthhousesettings',
            name='phone_number',
            field=models.CharField(default='+0123456789', max_length=28),
        ),
        migrations.AlterField(
            model_name='healthhousesettings',
            name='tagline',
            field=models.CharField(default='Some random tagline', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='discover_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='discover_title',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
