# Generated by Django 2.0.7 on 2018-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20180821_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthhousesettings',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
    ]
