# Generated by Django 2.0.7 on 2018-08-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20180821_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact page', 'verbose_name_plural': 'Contact pages'},
        ),
    ]
