# Generated by Django 2.0.7 on 2018-08-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_aboutpageteammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.IntegerField(choices=[(1, 'Founding partner'), (2, 'Structural partner'), (3, 'Other partner')], null=True),
        ),
    ]
