# Generated by Django 2.0.7 on 2018-08-23 12:10

from django.db import migrations
import home.moddels.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20180823_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverypage',
            name='content',
            field=wagtail.core.fields.StreamField([('parallax', home.moddels.blocks.ParagraphBlock()), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock()))], null=True),
        ),
    ]
