# Generated by Django 2.0.7 on 2018-08-23 12:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_discoverypage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverypage',
            name='content',
            field=wagtail.core.fields.StreamField([('parallax', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('primary', 'HH blue'), ('white', 'White'), ('dark-blue', 'HH dark')])), ('image_position', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')]))])), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock()))], null=True),
        ),
    ]
