# Generated by Django 2.0.7 on 2018-08-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20180823_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partners & visitors', 'verbose_name_plural': 'Partners & visitors'},
        ),
        migrations.AddField(
            model_name='partner',
            name='recent_visitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.IntegerField(choices=[(1, 'Founding partner'), (2, 'Structural partner'), (3, 'Other partner'), (4, 'No partner')], null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.URLField(verbose_name='Website'),
        ),
    ]
