# Generated by Django 2.0.7 on 2018-08-25 06:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20180824_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageVisitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_visitors', to='home.HomePage')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Partner')),
            ],
            options={
                'verbose_name': 'Recent visit',
                'verbose_name_plural': 'Recent visits',
            },
        ),
    ]
