# Generated by Django 2.0.7 on 2018-08-25 18:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20180825_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.HomePage')),
            ],
            options={
                'verbose_name': 'Core value',
                'verbose_name_plural': 'Core values',
            },
        ),
    ]
