# Generated by Django 2.0.7 on 2018-08-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_homepagefeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_text',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_title',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
