# Generated by Django 2.0.7 on 2018-08-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_auto_20180825_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='feature_text',
        ),
    ]
