# Generated by Django 2.0.7 on 2018-08-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_homepagemasonry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_info',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
