# Generated by Django 2.0.7 on 2018-08-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_auto_20180830_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='feature_title',
            field=models.CharField(max_length=63, null=True, verbose_name='title'),
        ),
    ]
