# Generated by Django 2.0.7 on 2018-08-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_auto_20180830_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefeatures',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homepagefeatures',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Core value'),
        ),
    ]
