# Generated by Django 2.0.7 on 2018-09-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0067_auto_20180830_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='discover_link2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='discover_link2_text',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='discover_link_text',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
