# Generated by Django 2.0.7 on 2018-09-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_homepagenumber_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bullet',
            name='number',
        ),
    ]
