# Generated by Django 2.0.7 on 2018-09-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_remove_bullet_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagenumber',
            old_name='tests',
            new_name='bullets',
        ),
    ]
