# Generated by Django 2.0.7 on 2018-09-03 19:15

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_interestingnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullet',
            name='test',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testmij', to='home.InterestingNumber'),
        ),
    ]
