# Generated by Django 2.0.7 on 2018-09-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_bullet_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestingnumber',
            name='bullets',
        ),
        migrations.RemoveField(
            model_name='bullet',
            name='test',
        ),
        migrations.DeleteModel(
            name='InterestingNumber',
        ),
    ]
