# Generated by Django 2.0.7 on 2018-09-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_auto_20180903_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagenumber',
            name='bullets',
        ),
    ]
