# Generated by Django 2.0.7 on 2018-09-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_remove_homepagenumber_bullets'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('identifier', models.CharField(max_length=28, verbose_name='label')),
                ('bullets', models.ManyToManyField(to='home.Bullet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
