# Generated by Django 2.0.7 on 2018-09-03 19:21

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_interestingnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestingnumber',
            name='bullets',
        ),
        migrations.AddField(
            model_name='bullet',
            name='number',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='home.InterestingNumber'),
        ),
    ]
