# Generated by Django 2.0.7 on 2018-09-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_auto_20180903_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagenumber',
            name='page',
        ),
        migrations.DeleteModel(
            name='HomePageNumber',
        ),
    ]
