# Generated by Django 2.0.7 on 2018-09-03 19:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_auto_20180903_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.InterestingNumber')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
