# Generated by Django 2.0.7 on 2018-09-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0081_auto_20180903_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthhouserelatedlink',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Link to page'),
        ),
    ]
