# Generated by Django 2.0.7 on 2018-09-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_healthhouserelatedlink_link_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='discover_link2_alternative',
            field=models.URLField(null=True, verbose_name='Link2 - Alternative'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='discover_link_alternative',
            field=models.URLField(null=True, verbose_name='Link1 - Alternative'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='discover_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Link1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='discover_link2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Link2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='discover_link2_text',
            field=models.CharField(max_length=32, null=True, verbose_name='Link2 text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='discover_link_text',
            field=models.CharField(max_length=32, null=True, verbose_name='Link text'),
        ),
    ]
