# Generated by Django 2.0.7 on 2018-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_auto_20180904_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='discover_link2_alternative',
            field=models.URLField(blank=True, null=True, verbose_name='Link2 - Alternative'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='discover_link_alternative',
            field=models.URLField(blank=True, null=True, verbose_name='Link1 - Alternative'),
        ),
    ]
