# Generated by Django 2.0.7 on 2018-09-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_contactpageformfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagevisitors',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagevisitors',
            name='visitor',
        ),
        migrations.DeleteModel(
            name='HomePageVisitors',
        ),
    ]
