# Generated by Django 2.0.7 on 2018-09-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_auto_20180906_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagenumber',
            name='number',
        ),
        migrations.RemoveField(
            model_name='homepagenumber',
            name='page',
        ),
        migrations.DeleteModel(
            name='HomePageNumber',
        ),
    ]
