# Generated by Django 2.0.7 on 2018-09-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_auto_20180906_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeatures',
            name='icon',
            field=models.CharField(choices=[('icon-ecommerce_graph3', 'Graph'), ('icon-basic_eye', 'Eye'), ('icon-basic_message_multiple', 'Text balloon')], max_length=40, null=True, verbose_name='Icon'),
        ),
    ]
