# Generated by Django 2.0.7 on 2018-09-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0090_homepagefeatures_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='aboutpageteammember',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
