# Generated by Django 2.0.7 on 2018-09-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_auto_20180911_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpageteammember',
            name='page',
        ),
    ]
