# Generated by Django 2.0.7 on 2018-09-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0092_remove_aboutpageteammember_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPageTeamMember',
            new_name='TeamMember',
        ),
    ]
