# Generated by Django 2.0.7 on 2018-09-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_auto_20180911_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagequestion',
            options={'ordering': ['sort_order'], 'verbose_name': 'FAQ question', 'verbose_name_plural': 'FAQ questions'},
        ),
    ]
