# Generated by Django 2.0.7 on 2018-09-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_auto_20180912_0651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagecoverimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Cover image', 'verbose_name_plural': 'Cover images'},
        ),
        migrations.AlterModelOptions(
            name='homepagefeatures',
            options={'ordering': ['sort_order'], 'verbose_name': 'Core value', 'verbose_name_plural': 'Core values'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['sort_order'], 'verbose_name': 'Team member', 'verbose_name_plural': 'Team members'},
        ),
    ]
