# Generated by Django 2.0.7 on 2018-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_storyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverydetailpage',
            name='discover_detail',
            field=models.CharField(choices=[('storylines', 'Storylines'), ('meeting_rooms', 'Meeting rooms'), ('expo_rooms', 'Exhibition areas')], max_length=28, null=True),
        ),
    ]
