# Generated by Django 2.0.7 on 2018-09-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_auto_20180913_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyline',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
