# Generated by Django 2.0.7 on 2018-09-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_storyline_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyline',
            old_name='partner',
            new_name='company',
        ),
    ]
