# Generated by Django 2.0.7 on 2018-09-13 10:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_auto_20180913_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralBullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ExpoAreaBullet',
            fields=[
                ('generalbullet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.GeneralBullet')),
                ('expo_area', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='home.ExpoArea')),
            ],
            bases=('home.generalbullet',),
        ),
    ]
