# Generated by Django 2.0.7 on 2018-09-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0110_expoareabullet_generalbullet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, null=True)),
                ('text', models.TextField(null=True)),
                ('link', models.URLField(null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.AlterField(
            model_name='discoverydetailpage',
            name='discover_detail',
            field=models.CharField(choices=[('storylines', 'Storylines'), ('meeting_rooms', 'Meeting rooms'), ('expo_rooms', 'Exhibition areas'), ('projects', 'Projects')], max_length=28, null=True),
        ),
    ]
