# Generated by Django 2.0.7 on 2018-09-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0112_project_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeatures',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='homepagefeatures',
            name='link_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
