# Generated by Django 2.0.7 on 2018-09-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0113_auto_20180913_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='homepagefeatures',
            name='link_title',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_title',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
