# Generated by Django 2.0.7 on 2018-09-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0115_testimonial_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='company',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
