# Generated by Django 2.0.7 on 2018-09-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0116_testimonial_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='founding_text',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='founding_title',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='structural_text',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='structural_title',
            field=models.CharField(max_length=28, null=True),
        ),
    ]
