# Generated by Django 2.0.7 on 2018-09-13 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0117_auto_20180913_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo_white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
