# Generated by Django 2.0.7 on 2018-09-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0118_partner_logo_white'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverydetailpage',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
