# Generated by Django 2.0.7 on 2018-09-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0008_document_file_size'),
        ('home', '0121_blogindexpage_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=300)),
                ('link', models.URLField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
            ],
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='press_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='press_title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
