# Generated by Django 2.0.7 on 2018-09-15 19:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0122_auto_20180915_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=28, verbose_name='Name')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Topic: (mission, vision, ...)',
                'verbose_name_plural': 'Topics: (mission, vision, ...)',
            },
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutpagetopic',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='home.AboutPage'),
        ),
    ]
