# Generated by Django 2.0.7 on 2018-09-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0123_auto_20180915_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagetopic',
            options={'verbose_name': 'Topic: (mission, vision, ...)', 'verbose_name_plural': 'Topics'},
        ),
    ]
