# Generated by Django 2.0.7 on 2018-09-16 10:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0124_auto_20180915_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBullet',
            fields=[
                ('generalbullet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.GeneralBullet')),
                ('project', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='home.Project')),
            ],
            bases=('home.generalbullet',),
        ),
        migrations.CreateModel(
            name='StorylineBullet',
            fields=[
                ('generalbullet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.GeneralBullet')),
                ('expo_area', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='home.Storyline')),
            ],
            bases=('home.generalbullet',),
        ),
        migrations.AlterModelOptions(
            name='meetingroom',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='aboutpagetopic',
            name='description',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
