# Generated by Django 2.0.7 on 2018-09-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0125_auto_20180916_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expoarea',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='storyline',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='storyline',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Partner'),
        ),
    ]
