# Generated by Django 2.0.7 on 2018-10-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0129_auto_20181014_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Core team'), (2, 'Board member'), (3, 'Brand ambassador')], verbose_name='Type'),
        ),
    ]
