# Generated by Django 2.0.7 on 2018-10-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0130_auto_20181015_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressarticle',
            name='document_link_title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='link_title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
