# Generated by Django 2.0.7 on 2018-10-18 13:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0131_auto_20181017_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverypage',
            name='content',
            field=wagtail.core.fields.StreamField([('parallax', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock(max_length=64)), ('info_text', wagtail.core.blocks.CharBlock(max_length=255)), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(), required=False)), ('external_links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=28, required=False))]), required=False)), ('mail_links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.EmailBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=28, required=False))]), required=False))]))], null=True),
        ),
    ]
