# Generated by Django 2.0.7 on 2018-10-18 14:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0133_directions_directionsbullet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionsBullets',
            fields=[
                ('generalbullet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.GeneralBullet')),
                ('directions', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='home.Directions')),
            ],
            bases=('home.generalbullet',),
        ),
        migrations.RemoveField(
            model_name='directionsbullet',
            name='number',
        ),
        migrations.DeleteModel(
            name='DirectionsBullet',
        ),
    ]
