# Generated by Django 2.0.7 on 2018-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0134_auto_20181018_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalbullet',
            name='item',
            field=models.CharField(max_length=128),
        ),
    ]
