# Generated by Django 2.0.7 on 2018-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0135_auto_20181018_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='transportation_means',
            field=models.CharField(choices=[('CAR', 'By car'), ('TRAIN', 'Train'), ('BUS', 'Bus')], max_length=32),
        ),
    ]
