# Generated by Django 2.0.7 on 2018-10-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0136_auto_20181018_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthhousesettings',
            name='error_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
