# Generated by Django 2.1.7 on 2019-02-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0140_privacypage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directions',
            options={'verbose_name': 'directions', 'verbose_name_plural': 'directions'},
        ),
    ]
