# Generated by Django 2.1.7 on 2019-03-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0142_auto_20190316_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendaritem',
            old_name='when',
            new_name='start',
        ),
    ]
