# Generated by Django 2.1.7 on 2019-03-18 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0143_auto_20190318_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritem',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
