# Generated by Django 2.1.7 on 2019-03-18 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0144_calendaritem_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritem',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='end',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
