# Generated by Django 2.1.7 on 2019-04-01 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0145_auto_20190318_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('calendaritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.CalendarItem')),
                ('max_attendees', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('event_type', models.IntegerField(choices=[(1, 'Public Thursday')], null=True)),
            ],
            bases=('home.calendaritem',),
        ),
        migrations.CreateModel(
            name='EventListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introduction', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='publicevent',
            name='calendaritem_ptr',
        ),
        migrations.DeleteModel(
            name='PublicEvent',
        ),
    ]
