# Generated by Django 2.1.7 on 2019-04-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0147_auto_20190406_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, verbose_name='External link'),
        ),
    ]
