# Generated by Django 2.1.7 on 2019-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0148_event_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Team member', 'verbose_name_plural': 'Team members'},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
