# Generated by Django 2.1.7 on 2019-05-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0149_auto_20190530_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Display order'),
        ),
    ]
