# Generated by Django 2.1.7 on 2019-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0151_auto_20190801_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='trusted_text',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='trusted_title',
            field=models.CharField(max_length=28, null=True),
        ),
    ]
