# Generated by Django 2.1.7 on 2019-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0152_auto_20190801_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private event?'),
        ),
    ]
