# Generated by Django 2.1.7 on 2019-08-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0154_privateeventlistpage_privateeventpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=30)),
                ('brings_guest', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=90)),
            ],
            options={
                'verbose_name': 'visitor',
                'verbose_name_plural': 'visitors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
