# Generated by Django 2.1.7 on 2019-08-30 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0155_eventvisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvisitor',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='home.Event'),
        ),
    ]
