# Generated by Django 2.1.7 on 2019-09-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0157_auto_20190901_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvisitor',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone numer'),
        ),
    ]
