# Generated by Django 2.1.7 on 2019-09-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0158_eventvisitor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateeventpage',
            name='event_information',
            field=models.TextField(null=True, verbose_name='Introduction text'),
        ),
        migrations.AddField(
            model_name='privateeventpage',
            name='question_text',
            field=models.TextField(null=True, verbose_name='Contact information'),
        ),
    ]
