# Generated by Django 2.1.7 on 2019-09-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0160_privateeventvisitorpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
