# Generated by Django 2.1.7 on 2019-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0161_auto_20190903_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='catering',
            field=models.IntegerField(choices=[(0, 'No catering'), (1, 'Sandwiches'), (2, 'Walking dinner'), (3, 'Reception')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Public Thursday'), (2, 'Private Event')], null=True),
        ),
        migrations.AlterField(
            model_name='eventvisitor',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone number'),
        ),
    ]
