# Generated by Django 2.1.7 on 2019-09-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0162_auto_20190917_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvisitor',
            name='diet_info',
            field=models.TextField(blank=True, null=True, verbose_name='Diet info'),
        ),
    ]
