# Generated by Django 2.1.7 on 2019-09-17 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0163_eventvisitor_diet_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvisitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventvisitor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
