# Generated by Django 2.1.15 on 2020-03-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0169_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateeventpage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Event'),
        ),
    ]
