# Generated by Django 2.1.15 on 2020-04-07 16:51

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0171_coronaarticlepage_coronaarticlepagetag_coronaindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronaarticlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.CoronaArticlePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
