# Generated by Django 2.1.15 on 2020-04-08 19:23

from django.db import migrations
import home.models.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0174_coronaarticlepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronaarticlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', home.models.blocks.ParagraphBlock()), ('rich_text', home.models.blocks.CustomRichTextBlock()), ('unordered_list', home.models.blocks.CustomListBlock(child_block=home.models.blocks.ListItemBlock))], null=True),
        ),
    ]
