# Generated by Django 2.1.15 on 2020-04-09 09:21

from django.db import migrations, models
import home.models.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0175_auto_20200408_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronaindexpage',
            name='intro',
            field=models.CharField(default='Introduction text here ...', max_length=512, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='coronaarticlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('subtitle', home.models.blocks.SubtitleBlock()), ('paragraph', home.models.blocks.ParagraphBlock()), ('rich_text', home.models.blocks.CustomRichTextBlock()), ('unordered_list', home.models.blocks.CustomListBlock(child_block=home.models.blocks.ListItemBlock)), ('link', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(max_lenght=64, required=True)), ('internal_link', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(), required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))]))], null=True),
        ),
    ]
