# Generated by Django 2.1.15 on 2020-04-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0176_auto_20200409_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronaarticlepage',
            name='author',
            field=models.CharField(max_length=64, null=True, verbose_name='Author or resource'),
        ),
    ]
