# Generated by Django 2.1.15 on 2020-04-09 19:18

from django.db import migrations
import home.models.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0177_coronaarticlepage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronaarticlepage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('embed', home.models.blocks.CustomEmbedBlock())], null=True),
        ),
    ]
