# Generated by Django 2.1.15 on 2020-04-10 07:38

from django.db import migrations, models
import home.models.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0179_auto_20200409_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronaarticlepage',
            name='author',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Author or resource'),
        ),
        migrations.AlterField(
            model_name='coronaarticlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('subtitle', home.models.blocks.CoronaSubtitleBlock()), ('paragraph', home.models.blocks.CoronaParagraphBlock()), ('rich_text', home.models.blocks.CoronaRichTextBlock()), ('unordered_list', home.models.blocks.CoronaListBlock(child_block=home.models.blocks.ListItemBlock)), ('link', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(max_lenght=64, required=True)), ('internal_link', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(), required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))]))], null=True),
        ),
    ]
