# Generated by Django 2.1.15 on 2020-04-10 07:52

from django.db import migrations
import home.models.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0180_auto_20200410_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronaarticlepage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('embed', home.models.blocks.CoronaEmbedBlock()), ('gallery', home.models.blocks.CoronaCarouselBlock(child_block=home.models.blocks.CoronaImageBlock))], null=True),
        ),
    ]
