# Generated by Django 3.1.1 on 2020-09-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0184_auto_20200730_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpageformfield',
            name='clean_name',
            field=models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name'),
        ),
    ]
