# Generated by Django 3.1.1 on 2020-09-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('home', '0186_auto_20200915_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
    ]
