# Generated by Django 3.1.1 on 2020-09-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0188_auto_20200921_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mailform_text',
            field=models.CharField(max_length=255, null=True, verbose_name='info text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mailform_title',
            field=models.CharField(max_length=63, null=True, verbose_name='title'),
        ),
    ]
