# Generated by Django 3.1.1 on 2020-09-21 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0189_auto_20200921_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='expoarea',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storyline',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
