# Generated by Django 3.1.1 on 2020-09-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0190_auto_20200921_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expoarea',
            options={'ordering': ['last_edited']},
        ),
        migrations.AlterModelOptions(
            name='meetingroom',
            options={'ordering': ['last_edited']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['last_edited']},
        ),
        migrations.AlterModelOptions(
            name='storyline',
            options={'ordering': ['last_edited']},
        ),
    ]
