# Generated by Django 3.1.8 on 2021-08-25 16:31

from django.db import migrations
import home.models.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0192_auto_20210307_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronaarticlepage',
            name='fullwidth',
            field=wagtail.core.fields.StreamField([('gallery', home.models.blocks.CoronaCarouselBlock(child_block=home.models.blocks.CoronaImageBlock)), ('embed', home.models.blocks.CoronaEmbedBlock())], null=True),
        ),
    ]
