# Generated by Django 3.1.8 on 2022-02-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0201_auto_20220204_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsoverviewcategory',
            name='hide',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionspage',
            name='category',
            field=models.IntegerField(choices=[(1, 'Answers'), (2, 'Testimonials'), (3, 'Experience'), (4, 'Innovations')], default=1),
        ),
    ]
